package com.ifce.dailypoint.exceptions;

public enum BusinessErrorEnum {
    
    ENTERPRISE_NOT_FOUND,
    INVALID_TOKEN,
    EXPIRED_TOKEN,
    INVALID_PASSWORD,
    USERNAME_ALREADY_EXISTS,
    INVALID_PARAMETER,
    USER_NOT_AUTHORIZED,
    USERNAME_NOT_FOUND,
    EMPLOYEE_NOT_FOUND,
    INVALID_DATE,
    EMPLOYEE_ALREADY_EXISTS,
    ENTERPRISE_ALREADY_EXISTS;
}
